# ~/.config/starship.toml

add_newline = true

# A minimal left prompt
format = """$directory$character"""

# move the rest of the prompt to the right
right_format = """$all"""

[directory]
truncation_length = 8
truncation_symbol = "…/"

[aws]
format = "([$symbol $profile]($style))"
style = "bold yellow"
symbol = "☁️ "
# disabled = true
