# ~/.config/starship.toml

# A minimal left prompt
format = """$directory$character"""

# move the rest of the prompt to the right
right_format = """$all"""

[directory]
truncation_length = 8
truncation_symbol = "…/"

[aws]
format = "on [$symbol$profile]($style) "
style = "bold yellow"
symbol = "☁️ "
disabled = true
