return {
  { "akinsho/bufferline.nvim" },
  { "catppuccin/nvim", lazy = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "edeneast/nightfox.nvim", lazy = false },
  {
    "Exafunction/codeium.nvim",
    lazy = true,
    opts = {
      enterprise_mode = true,
      api = { host = "enterprise-url.com", path = "/_route/api_server" },
    },
    enabled = false,
  },
  { "f-person/git-blame.nvim" },
  { "folke/tokyonight.nvim", lazy = false },
  { "fynnfluegge/monet.nvim", lazy = false },
  { "lewis6991/gitsigns.nvim", opts = { _extmark_signs = false } },
  { "NeogitOrg/neogit", dependencies = { "nvim-lua/plenary.nvim", "sindrets/diffview.nvim" }, config = true },
  { "nvim-telescope/telescope-symbols.nvim" },
  { "nvim-telescope/telescope.nvim", lazy = false },
  { "nvim-tree/nvim-tree.lua", enabled = false },
  { "s1n7ax/nvim-window-picker" },
  { "tpope/vim-fugitive" },
  { "whatyouhide/vim-gotham", lazy = false },
}
